#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bennington.Cms.Views.ListDetail
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ListDetail\Helpers.cshtml"
    using Bennington.Core.List;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    public static class Helpers
    {

public static System.Web.WebPages.HelperResult RenderListColumns(this HtmlHelper htmlHelper, ListColumns columns)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "..\..\Views\ListDetail\Helpers.cshtml"
 
    foreach (var column in columns)
    {
        
#line default
#line hidden


#line 7 "..\..\Views\ListDetail\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlHelper.RenderListColumn(column));

#line default
#line hidden


#line 7 "..\..\Views\ListDetail\Helpers.cshtml"
                                            
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderListColumn(this HtmlHelper htmlHelper, ListColumn column)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 12 "..\..\Views\ListDetail\Helpers.cshtml"
 
    if (column.HasHeaderTemplate)
    {
        htmlHelper.RenderPartial(column.HeaderTemplate, column);
    }
    else
    {             

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <th ");



#line 19 "..\..\Views\ListDetail\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, SortClass(column));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n        <a href=\"");



#line 20 "..\..\Views\ListDetail\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.SortUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 20 "..\..\Views\ListDetail\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.DisplayName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n    </th>\r\n");



#line 22 "..\..\Views\ListDetail\Helpers.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult SortClass(ListColumn column)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 25 "..\..\Views\ListDetail\Helpers.cshtml"
 
    if (column.IsSorted)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "class=\"");



#line 28 "..\..\Views\ListDetail\Helpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, column.SortDirection.GetValueOrDefault().ToString().ToLower());

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"\r\n");



#line 29 "..\..\Views\ListDetail\Helpers.cshtml"
    }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
