//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Paragon.ContentTree.ToolLinkNodeProvider.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ToolLinkProviderDataModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ToolLinkProviderDataModel object using the connection string found in the 'ToolLinkProviderDataModel' section of the application configuration file.
        /// </summary>
        public ToolLinkProviderDataModel() : base("name=ToolLinkProviderDataModel", "ToolLinkProviderDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ToolLinkProviderDataModel object.
        /// </summary>
        public ToolLinkProviderDataModel(string connectionString) : base(connectionString, "ToolLinkProviderDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ToolLinkProviderDataModel object.
        /// </summary>
        public ToolLinkProviderDataModel(EntityConnection connection) : base(connection, "ToolLinkProviderDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ToolLinkProviderDraft> ToolLinkProviderDrafts
        {
            get
            {
                if ((_ToolLinkProviderDrafts == null))
                {
                    _ToolLinkProviderDrafts = base.CreateObjectSet<ToolLinkProviderDraft>("ToolLinkProviderDrafts");
                }
                return _ToolLinkProviderDrafts;
            }
        }
        private ObjectSet<ToolLinkProviderDraft> _ToolLinkProviderDrafts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ToolLinkProviderDrafts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToolLinkProviderDrafts(ToolLinkProviderDraft toolLinkProviderDraft)
        {
            base.AddObject("ToolLinkProviderDrafts", toolLinkProviderDraft);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Paragon.ContentTree.ToolLinkNodeProvider.Data", Name="ToolLinkProviderDraft")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ToolLinkProviderDraft : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ToolLinkProviderDraft object.
        /// </summary>
        /// <param name="toolLinkId">Initial value of the ToolLinkId property.</param>
        public static ToolLinkProviderDraft CreateToolLinkProviderDraft(global::System.String toolLinkId)
        {
            ToolLinkProviderDraft toolLinkProviderDraft = new ToolLinkProviderDraft();
            toolLinkProviderDraft.ToolLinkId = toolLinkId;
            return toolLinkProviderDraft;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToolLinkId
        {
            get
            {
                return _ToolLinkId;
            }
            set
            {
                if (_ToolLinkId != value)
                {
                    OnToolLinkIdChanging(value);
                    ReportPropertyChanging("ToolLinkId");
                    _ToolLinkId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ToolLinkId");
                    OnToolLinkIdChanged();
                }
            }
        }
        private global::System.String _ToolLinkId;
        partial void OnToolLinkIdChanging(global::System.String value);
        partial void OnToolLinkIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TreeNodeId
        {
            get
            {
                return _TreeNodeId;
            }
            set
            {
                OnTreeNodeIdChanging(value);
                ReportPropertyChanging("TreeNodeId");
                _TreeNodeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TreeNodeId");
                OnTreeNodeIdChanged();
            }
        }
        private global::System.String _TreeNodeId;
        partial void OnTreeNodeIdChanging(global::System.String value);
        partial void OnTreeNodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private Nullable<global::System.Int32> _Sequence;
        partial void OnSequenceChanging(Nullable<global::System.Int32> value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlSegment
        {
            get
            {
                return _UrlSegment;
            }
            set
            {
                OnUrlSegmentChanging(value);
                ReportPropertyChanging("UrlSegment");
                _UrlSegment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlSegment");
                OnUrlSegmentChanged();
            }
        }
        private global::System.String _UrlSegment;
        partial void OnUrlSegmentChanging(global::System.String value);
        partial void OnUrlSegmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion
    
    }

    #endregion
    
}
