"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.AdminAccounts/Views/AdminAccount/Edit.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.AdminAccounts/Views/AdminAccount/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/Error.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms.PrincipalProvider/Views/User/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms.PrincipalProvider/Views/User/Modify.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Engines.ContactUs/Views/ContactUs/Confirmation.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Engines.ContactUs/Views/ContactUs/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Engines.Faq/Views/Faq/About.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Engines.Faq/Views/Faq/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Engines.Homepage/Views/Homepage/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Engines.Homepage/Views/HomepageContentTreeNode/Modify.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.ContentNodeProvider/Views/ContentTreeNode/ContentItemNavigation.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.ContentNodeProvider/Views/ContentTreeNode/Display.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.ContentNodeProvider/Views/ContentTreeNode/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.ContentNodeProvider/Views/ContentTreeNode/Modify.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.SectionNodeProvider/Views/ContentTreeSectionNode/Modify.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.ToolLinkNodeProvider/Views/ToolLinkProviderNode/Modify.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Login/Views/Login/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleApp/Views/Location/Edit.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleApp/Views/Location/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Routes.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Account/ChangePassword.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Account/ChangePasswordSuccess.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Account/LogOn.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Account/Register.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Home/About.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Home/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Shared/Error.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleFeature/Views/Example/About.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleFeature/Views/Example/Index.aspx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/ButtonsForEditForm.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayForObject.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/Button.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/DateTime.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/DoNotShowThisProperty.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/ListPageViewModel`1.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/RoutesButton.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/String.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/SubmitButton.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/DisplayTemplates/UrlButton.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorForObject.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/Boolean.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/CheckboxList.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/Console.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/DateTime.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/Dropdown.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/EditForm.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/Hidden.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/HtmlEditor.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/RadioButtonList.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/EditorTemplates/String.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/ListPageViewModel_Footer.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/ListPageViewModel_Header.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/ListPageViewModel_PagerHeaders.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Cms/Views/Shared/SingleRowForListPage.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree/Views/Shared/EditorTemplates/ProviderTypes.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.ContentNodeProvider/Views/Shared/EditorTemplates/ContentTreeNodeInputModel.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.ContentTree.Providers.SectionNodeProvider/Views/Shared/EditorTemplates/DefaultTreeNodeId.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Login/Views/Login/EditorTemplates/LoginForm.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Login/Views/Login/EditorTemplates/Password.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Login/Views/Login/EditorTemplates/String.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/Bennington.Login/Views/Login/Styles.ascx
"C:\_Application\fuck\aspx2razor\bin\Debug\aspx2razor.exe" ./src/SampleContentWebsite/Views/Shared/LogOnUserControl.ascx