#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paragon.ContentTree.SectionNodeProvider.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paragon")]
	public partial class ContentTreeSectionNodeProviderDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertContentTreeSectionNode(ContentTreeSectionNode instance);
    partial void UpdateContentTreeSectionNode(ContentTreeSectionNode instance);
    partial void DeleteContentTreeSectionNode(ContentTreeSectionNode instance);
    #endregion
		
		public ContentTreeSectionNodeProviderDataModelDataContext() : 
				base(global::Paragon.ContentTree.SectionNodeProvider.Properties.Settings.Default.ParagonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ContentTreeSectionNode> ContentTreeSectionNodes
		{
			get
			{
				return this.GetTable<ContentTreeSectionNode>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContentTreeSectionNode")]
	public partial class ContentTreeSectionNode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Key;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _LastModifyDate;
		
		private string _LastModifyBy;
		
		private string _TreeNodeId;
		
		private string _UrlSegment;
		
		private System.Nullable<int> _Sequence;
		
		private string _Name;
		
		private string _DefaultTreeNodeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeyChanging(int value);
    partial void OnKeyChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnLastModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifyDateChanged();
    partial void OnLastModifyByChanging(string value);
    partial void OnLastModifyByChanged();
    partial void OnTreeNodeIdChanging(string value);
    partial void OnTreeNodeIdChanged();
    partial void OnUrlSegmentChanging(string value);
    partial void OnUrlSegmentChanged();
    partial void OnSequenceChanging(System.Nullable<int> value);
    partial void OnSequenceChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDefaultTreeNodeIdChanging(string value);
    partial void OnDefaultTreeNodeIdChanged();
    #endregion
		
		public ContentTreeSectionNode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this.OnKeyChanging(value);
					this.SendPropertyChanging();
					this._Key = value;
					this.SendPropertyChanged("Key");
					this.OnKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(100)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifyDate
		{
			get
			{
				return this._LastModifyDate;
			}
			set
			{
				if ((this._LastModifyDate != value))
				{
					this.OnLastModifyDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifyDate = value;
					this.SendPropertyChanged("LastModifyDate");
					this.OnLastModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifyBy", DbType="NVarChar(100)")]
		public string LastModifyBy
		{
			get
			{
				return this._LastModifyBy;
			}
			set
			{
				if ((this._LastModifyBy != value))
				{
					this.OnLastModifyByChanging(value);
					this.SendPropertyChanging();
					this._LastModifyBy = value;
					this.SendPropertyChanged("LastModifyBy");
					this.OnLastModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeNodeId", DbType="NVarChar(100)")]
		public string TreeNodeId
		{
			get
			{
				return this._TreeNodeId;
			}
			set
			{
				if ((this._TreeNodeId != value))
				{
					this.OnTreeNodeIdChanging(value);
					this.SendPropertyChanging();
					this._TreeNodeId = value;
					this.SendPropertyChanged("TreeNodeId");
					this.OnTreeNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlSegment", DbType="NVarChar(500)")]
		public string UrlSegment
		{
			get
			{
				return this._UrlSegment;
			}
			set
			{
				if ((this._UrlSegment != value))
				{
					this.OnUrlSegmentChanging(value);
					this.SendPropertyChanging();
					this._UrlSegment = value;
					this.SendPropertyChanged("UrlSegment");
					this.OnUrlSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sequence", DbType="Int")]
		public System.Nullable<int> Sequence
		{
			get
			{
				return this._Sequence;
			}
			set
			{
				if ((this._Sequence != value))
				{
					this.OnSequenceChanging(value);
					this.SendPropertyChanging();
					this._Sequence = value;
					this.SendPropertyChanged("Sequence");
					this.OnSequenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultTreeNodeId", DbType="nvarchar(100)")]
		public string DefaultTreeNodeId
		{
			get
			{
				return this._DefaultTreeNodeId;
			}
			set
			{
				if ((this._DefaultTreeNodeId != value))
				{
					this.OnDefaultTreeNodeIdChanging(value);
					this.SendPropertyChanging();
					this._DefaultTreeNodeId = value;
					this.SendPropertyChanged("DefaultTreeNodeId");
					this.OnDefaultTreeNodeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
