#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paragon.ContentTree.SectionNodeProvider.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paragon")]
	public partial class ContentTreeSectionNodeProviderDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSectionNodeProviderDraft(SectionNodeProviderDraft instance);
    partial void UpdateSectionNodeProviderDraft(SectionNodeProviderDraft instance);
    partial void DeleteSectionNodeProviderDraft(SectionNodeProviderDraft instance);
    #endregion
		
		public ContentTreeSectionNodeProviderDataModelDataContext() : 
				base(global::Paragon.ContentTree.SectionNodeProvider.Properties.Settings.Default.ParagonConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContentTreeSectionNodeProviderDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SectionNodeProviderDraft> SectionNodeProviderDrafts
		{
			get
			{
				return this.GetTable<SectionNodeProviderDraft>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SectionNodeProviderDraft")]
	public partial class SectionNodeProviderDraft : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SectionId;
		
		private string _TreeNodeId;
		
		private System.Nullable<int> _Sequence;
		
		private string _Name;
		
		private string _UrlSegment;
		
		private string _DefaultTreeNodeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSectionIdChanging(string value);
    partial void OnSectionIdChanged();
    partial void OnTreeNodeIdChanging(string value);
    partial void OnTreeNodeIdChanged();
    partial void OnSequenceChanging(System.Nullable<int> value);
    partial void OnSequenceChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUrlSegmentChanging(string value);
    partial void OnUrlSegmentChanged();
    partial void OnDefaultTreeNodeIdChanging(string value);
    partial void OnDefaultTreeNodeIdChanged();
    #endregion
		
		public SectionNodeProviderDraft()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionId", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this.OnSectionIdChanging(value);
					this.SendPropertyChanging();
					this._SectionId = value;
					this.SendPropertyChanged("SectionId");
					this.OnSectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeNodeId", DbType="NVarChar(100)")]
		public string TreeNodeId
		{
			get
			{
				return this._TreeNodeId;
			}
			set
			{
				if ((this._TreeNodeId != value))
				{
					this.OnTreeNodeIdChanging(value);
					this.SendPropertyChanging();
					this._TreeNodeId = value;
					this.SendPropertyChanged("TreeNodeId");
					this.OnTreeNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sequence", DbType="Int")]
		public System.Nullable<int> Sequence
		{
			get
			{
				return this._Sequence;
			}
			set
			{
				if ((this._Sequence != value))
				{
					this.OnSequenceChanging(value);
					this.SendPropertyChanging();
					this._Sequence = value;
					this.SendPropertyChanged("Sequence");
					this.OnSequenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlSegment", DbType="NVarChar(500)")]
		public string UrlSegment
		{
			get
			{
				return this._UrlSegment;
			}
			set
			{
				if ((this._UrlSegment != value))
				{
					this.OnUrlSegmentChanging(value);
					this.SendPropertyChanging();
					this._UrlSegment = value;
					this.SendPropertyChanged("UrlSegment");
					this.OnUrlSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultTreeNodeId", DbType="NVarChar(100)")]
		public string DefaultTreeNodeId
		{
			get
			{
				return this._DefaultTreeNodeId;
			}
			set
			{
				if ((this._DefaultTreeNodeId != value))
				{
					this.OnDefaultTreeNodeIdChanging(value);
					this.SendPropertyChanging();
					this._DefaultTreeNodeId = value;
					this.SendPropertyChanged("DefaultTreeNodeId");
					this.OnDefaultTreeNodeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
