//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Paragon.ContentTree.ExampleEngineNodeProvider.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ContentTreecontactUsNodeDataModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ContentTreecontactUsNodeDataModel object using the connection string found in the 'ContentTreecontactUsNodeDataModel' section of the application configuration file.
        /// </summary>
        public ContentTreecontactUsNodeDataModel() : base("name=ContentTreecontactUsNodeDataModel", "ContentTreecontactUsNodeDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContentTreecontactUsNodeDataModel object.
        /// </summary>
        public ContentTreecontactUsNodeDataModel(string connectionString) : base(connectionString, "ContentTreecontactUsNodeDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContentTreecontactUsNodeDataModel object.
        /// </summary>
        public ContentTreecontactUsNodeDataModel(EntityConnection connection) : base(connection, "ContentTreecontactUsNodeDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentTreeContactUsNode> ContentTreeContactUsNodes
        {
            get
            {
                if ((_ContentTreeContactUsNodes == null))
                {
                    _ContentTreeContactUsNodes = base.CreateObjectSet<ContentTreeContactUsNode>("ContentTreeContactUsNodes");
                }
                return _ContentTreeContactUsNodes;
            }
        }
        private ObjectSet<ContentTreeContactUsNode> _ContentTreeContactUsNodes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentTreeContactUsNodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentTreeContactUsNodes(ContentTreeContactUsNode contentTreeContactUsNode)
        {
            base.AddObject("ContentTreeContactUsNodes", contentTreeContactUsNode);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Paragon.ContentTree.ExampleEngineNodeProvider.Data", Name="ContentTreeContactUsNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentTreeContactUsNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentTreeContactUsNode object.
        /// </summary>
        /// <param name="key">Initial value of the Key property.</param>
        public static ContentTreeContactUsNode CreateContentTreeContactUsNode(global::System.Int32 key)
        {
            ContentTreeContactUsNode contentTreeContactUsNode = new ContentTreeContactUsNode();
            contentTreeContactUsNode.Key = key;
            return contentTreeContactUsNode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.Int32 _Key;
        partial void OnKeyChanging(global::System.Int32 value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreateBy
        {
            get
            {
                return _CreateBy;
            }
            set
            {
                OnCreateByChanging(value);
                ReportPropertyChanging("CreateBy");
                _CreateBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreateBy");
                OnCreateByChanged();
            }
        }
        private global::System.String _CreateBy;
        partial void OnCreateByChanging(global::System.String value);
        partial void OnCreateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifyDate
        {
            get
            {
                return _LastModifyDate;
            }
            set
            {
                OnLastModifyDateChanging(value);
                ReportPropertyChanging("LastModifyDate");
                _LastModifyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifyDate");
                OnLastModifyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifyDate;
        partial void OnLastModifyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifyBy
        {
            get
            {
                return _LastModifyBy;
            }
            set
            {
                OnLastModifyByChanging(value);
                ReportPropertyChanging("LastModifyBy");
                _LastModifyBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModifyBy");
                OnLastModifyByChanged();
            }
        }
        private global::System.String _LastModifyBy;
        partial void OnLastModifyByChanging(global::System.String value);
        partial void OnLastModifyByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TreeNodeId
        {
            get
            {
                return _TreeNodeId;
            }
            set
            {
                OnTreeNodeIdChanging(value);
                ReportPropertyChanging("TreeNodeId");
                _TreeNodeId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TreeNodeId");
                OnTreeNodeIdChanged();
            }
        }
        private global::System.String _TreeNodeId;
        partial void OnTreeNodeIdChanging(global::System.String value);
        partial void OnTreeNodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private Nullable<global::System.Int32> _Sequence;
        partial void OnSequenceChanging(Nullable<global::System.Int32> value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlSegment
        {
            get
            {
                return _UrlSegment;
            }
            set
            {
                OnUrlSegmentChanging(value);
                ReportPropertyChanging("UrlSegment");
                _UrlSegment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlSegment");
                OnUrlSegmentChanged();
            }
        }
        private global::System.String _UrlSegment;
        partial void OnUrlSegmentChanging(global::System.String value);
        partial void OnUrlSegmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
    }

    #endregion
    
}
